### ISSUE TITLE
Nice ideas!

### ISSUE THREAD

**Issue by alexnm** [iraycd/React-Redux-Styleguide#3]
Hey, sorry in advance for opening this as an issues, but it's the easiest way to start a discussion I guess :)

I picked your repo from a newsletter and I liked what I read especially on the redux side. I developed this extension of the original ducks proposal called re-ducks (https://github.com/alexnm/re-ducks) which may also be of interest to you. Feel free to give feedback there or propose any changes. Also, if you have any showcase repositories with this particular redux structure, I'd love to link it from my page.

Cheers!
Alex

**Comment by iraycd** [comment]
As this is knowledge sharing repo more than Code. I don’t have a problem with most of issues.

I love your approach on ducks.
But, I have been using a similar approach.

Can you go in depth or example where on how to use selectors with multiple state.

Secondly, can you elaborate this. 

**NOTE:** Selector functions will be used outside the duck folder, so they are part of the interface of the duck.

**Comment by iraycd** [comment]
```
const mySelectorA = state => state.a
const mySelectorB = state => state.b

// The result function in the following selector
// is simply building an object from the input selectors
const structuredSelector = createSelector(
   mySelectorA,
   mySelectorB,
   mySelectorC,
   (a, b, c) => ({
     a,
     b,
     c
   })
)
```
It's not a prefect example. 
But, what if I have `state.a` and `state.a ` in different modules/ducks?

**Comment by alexnm** [comment]
I see ... I'm not that familiar with this as I'm not using reselect (I think that's the case here)

**Comment by iraycd** [comment]
Let's take a selector where we have to mix 2 states, `getVisibleTodos`, `isUserAuthenticated` and make a new selector.

```javascript
function getVisibleTodosOfUser( todos, user ) {
    // DO SOMETHING.
}
```

**Comment by alexnm** [comment]
as I mentioned, I haven't tried reselect and combining state from multiple parts of the redux store is not a problem when you just use mapStateToProps and regular functions because you can send the exact state part you need

**Comment by iraycd** [comment]
`combining state from multiple parts of the redux store is not a problem when you just use mapStateToProps and regular functions because you can send the exact state part you need`

Combing after `mapStateToProps`, can you give me an example? 
How is a better approach, than doing it before?

**Comment by alexnm** [comment]
I'm referring to something like this:
```javascript
function mapStateToProps( state ) {
  todos: todoSelectors.getVisibleTodos( state.todos, state.user )
}
```

where getVisibleTodos is a simple javascript function that acts on the entire state tree.
